### ISSUE TITLE
add design of the powerpoint

### ISSUE THREAD

**Issue by shawn-AI-Tech** [CyberTimon/powerpointer#4]
Hello, thank you for your great work. I would like to know how to add my own design of the powerpoint？

**Comment by CyberTimon** [comment]
Hello and thank you!

It's a bit hard and complicated to provide a step by step tutorial but here is what you basically need to do:

1. In PowerPoint, create a new powerpoint with a template. Then delete every slide. Then you need to check if your template has the following layout indicies which are defined in the app.py script:
layout_indices = [1, 7, 8] 
You can check this by clicking new slide and you will see if the structure (title and content) of the powerpoint matches these indices. 
2. Export the powerpoint without a slide (every slide deleted) and name it for example Design-8.pptx.
3. Add the option in the script that it will check if the number is highter than 8 instead of 7.

Hope this somehow works. - You need to understand how the code works to do this correctly I think.

**Comment by CyberTimon** [comment]
I'm closing this issue because I get no response. Feel free to reopen the issue when you have additional questions.
