### ISSUE TITLE
Powerpoint not working

### ISSUE THREAD

**Issue by OCDDX** [CyberTimon/powerpointer#7]
Hey, how can i increase the number of slides apart from the prompt? I changed the prompt, but i can't get powerpoint to generate more than 10 slides

and often times, when the powerpoint downloads, sometimes its jsut showing a grey screen saying "click here to insert first slide" and then theres no content inside obviously.. any suggestions?

I love this so much thanks for this, its answered all my prayers

**Comment by CyberTimon** [comment]
Hey there!

I can't really change much to make it generate more than 10 slides. The model itself stops when it thinks it has finished. 
It works really well for me when I say at the end of the topic "(At least 25 slides)". Most of the time, it does it. The code doesn't stop at X amount of slides.

To the second issue, openai often updates their models and it seems that the model sometimes don't want to follow the powerpoint prompt template. I also can't really change much here too. 

Hope this answers your questions. If you are a technical person, take a look at my offline powerpoint generator. This seems to work more consistent but is much harder to set up properly. (https://github.com/CyberTimon/Powerpointer-For-Local-LLMs)

Kind regards,
Timon Käch

**Comment by OCDDX** [comment]
Hey! thanks for your reply, i actually got it to work better now, it's FANTASTIC honestly. Thank you for creating this, i have been trying to do something like this for a while and i'm happy i decided to check whats out there.

How do you get it to generate you more unique ideas let's say. I changed the prompt in the app.py but i'm not sure what the proper format would be, would i include it like this for example:

Slide 2:

#Create a unique idea for xxxx

or would i include an example of the idea itself?

Many thanks, will look into your LLM,i'm not a technical person but i love a challenge!

Thanks again

**Comment by CyberTimon** [comment]
Hey! 

Thank you for your kind words.
I would not change the powerpoint prompt format. Leave that how it is, otherwise the slides won't get filled correctly and you will get empty presentations. 
To make it generate more diverse things, you can change line 25 in app.py from `-You make the presentation easy to understand.` to something like `-You make the presentations unique, diverse and something special`

In addition, you can easily just say when you enter the topic that it should generate diverse content at slide 2 in natural language. For example `Car history (Make slide 3 very unique about X) -5` 

Hope this helps!

Kind regards,
Timon Käch
